//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 由 SpaceLaunchSystem.rc 使用
//
#define IDR_MAINFRAME					128
#define IDM_ABOUTBOX					0x0010
#define IDD_ABOUTBOX					100
#define IDS_ABOUTBOX					101
#define IDD_SPACELAUNCHSYSTEM_DIALOG				102
#define IDD_MISSION_EDIT_DIALOG				129
#define IDC_EDIT_MISSION_ID				1000
#define IDC_EDIT_MISSION_NAME				1001
#define IDC_EDIT_ROCKET_NAME				1002
#define IDC_EDIT_PAYLOAD_NAME				1003
#define IDC_COMBO_DESTINATION				1004
#define IDC_EDIT_LAUNCH_TIME				1005

// 新对象的下一组默认值
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE	130
#define _APS_NEXT_CONTROL_VALUE		1006
#define _APS_NEXT_SYMED_VALUE		101
#define _APS_NEXT_COMMAND_VALUE		32771
#endif
#endif
